Make Manjaro installation procedure easier to read
t2linux/wiki pull request #180
Opened 2021-11-11 02:01 UTC by appleplectic

Grammatical changes, and some clarifications.

2021-11-11 02:07 UTC, nikodunk commented
Wow. Excellent job. Shame I just forked the Manjaro guide into Fedora before you did this :)

2021-11-11 06:43 UTC, networkException requested changes

2021-11-11 06:43 UTC, networkException commented on docs/distributions/manjaro/installation.md
> +2. Flash your Manjaro ISO to a USB Stick. If you want an easier way to do this. Use [Balena Etcher](https://www.balena.io/etcher/). For Terminal users, use dd.
I'd change this to "Terminal users can also use dd"

2021-11-12 07:09 UTC, networkException approved these changes

2021-11-12 07:12 UTC, merged