Add tips for contributing, update State article
t2linux/wiki pull request #487
Opened 2023-12-16 06:28 UTC by netnef

For the State article, I made these changes:

* Convert the layout to a table (lmk if you don't like it)
* Update the info to match the latest progress
* Add links/issues to some features for reference

Preview: https://netnef.github.io/wiki/state/

2023-12-16 06:33 UTC, sharpenedblade commented
> There is work in progress support for custom graphics on the Touch Bar.

Its not really WIP anymore, it should just say that its supported

> Trackpad  🟡 Partially working

It should be marked as working, but leave the note there. Same with audio.

2023-12-16 08:07 UTC, AdityaGarg8 commented
Wi-Fi and Bluetooth drivers are upstreamed. Also, Bluetooth is partially working for BCM4377 devices. On other devices too, it's not very stable.

2023-12-16 08:07 UTC, AdityaGarg8 requested changes
See latest comment

2023-12-16 12:27 UTC, AdityaGarg8 commented
I added a commit in your pr so that there is no clash.

2023-12-16 12:47 UTC, Redecorating reviewed
having a table here is much better

2023-12-16 12:47 UTC, Redecorating commented on docs/state.md
> +|Camera|🟢 Working|🟢 Yes|||
maybe note that this relies on apple-bce

2023-12-16 12:47 UTC, Redecorating commented on docs/state.md
> +|Screen|🟢 Working|🟢 Yes|||
patch to fix overscan on intel gpu is not upstream yet afaik

2023-12-16 12:47 UTC, Redecorating commented on docs/state.md
> +|Suspend|🟡 Partially working|🟢 Yes|A firmware upgrade attached to macOS Sonoma broke suspend. Some users were having difficulty with it even before Sonoma.|[#53](https://github.com/t2linux/T2-Ubuntu-
can you note that this sonoma issue is in the apple-bce module (because suspend does work if you don't use that module)

2023-12-16 12:47 UTC, Redecorating commented on docs/state.md
> +|Hybrid Graphics|🟡 Partially working|🟡 Partial|If the device has a dedicated AMD GPU (15 and 16 inch MacBookPro's) as well as an Intel iGPU, the iGPU can be used, but this breaks resume.|[Hybrid Grap
using igpu no longer breaks resume so you can remove that bit. maybe also mention that toggling the dgpu power doesn't work

2023-12-16 12:47 UTC, Redecorating commented on docs/state.md
> +|Bluetooth|🟢 Working|🔴 No|Requires macOS firmware only for devices with BCM4377 chip. Also, Bluetooth glitches on devices with BCM4377 Chip if connected to a 2.4 Ghz Wi-Fi connection. Thus, in order
bluetooth is upstream

2023-12-16 14:22 UTC, netnef commented
I updated the State article to address all of the comments here. I also added "Thunderbolt" to the features list.

Preview: https://netnef.github.io/wiki/state/

There's one last thing I wanted to ask about:

> Some models have deadzones on the edges of their trackpads where swipes along the trackpad that start in these deadzones will not be registered.

Is this still an issue? Is there a list of affected models anywhere?

2023-12-16 14:57 UTC, AdityaGarg8 commented
> I updated the State article to address all of the comments here. I also added "Thunderbolt" to the features list.
> 
> Preview: https://netnef.github.io/wiki/state/
> 
> There's one last thing I wanted to ask about:
> 
> > Some models have deadzones on the edges of their trackpads where swipes along the trackpad that start in these deadzones will not be registered.
> 
> Is this still an issue? Is there a list of affected models anywhere?

Tbh not enough feedback there by the users. Today only mbp 16,2 got fixed.

2023-12-16 17:16 UTC, netnef commented
Ok, then we can leave the notice there I guess. But I would still leave the status as "working" because for most models it works as well as it possibly can (using libinput, at least). We should probably also add details about how to use the Synaptics driver (with a disclaimer that it's unsupported and requires using deprecated X11 instead of Wayland). smileBeda provided instructions in the Discord for this. We can maybe paste those into a gist or wiki article.

2023-12-17 09:03 UTC, AdityaGarg8 commented
The gist is already in the wiki, you can put working as well

2023-12-17 09:03 UTC, AdityaGarg8 commented
Also, fix the lint errors please

2023-12-18 22:40 UTC, netnef commented
> The gist is already in the wiki, you can put working as well

Do you have a link to that so I can include it here?

2023-12-19 06:09 UTC, AdityaGarg8 commented
https://wiki.t2linux.org/#guides-and-similar

I don't think we need to put it here though. But status as working should be put.

2023-12-19 20:44 UTC, netnef commented
The reason I think we should reference it here is because of the note we have added to it:

> Works, but isn't as great as on macOS

On the other wiki page you linked, it says that you can obtain this:

> Implement macOS-like Keyboard and trackpad experience

I don't think adding a casual mention to it would hurt. Something like this:

> Works, but isn't as great as on macOS (no force touch or palm rejection). Some models have deadzones on the edges of their trackpads where swipes along the trackpad that start in these deadzones will not be registered. Using Synaptics + X11 as per [this guide](https://wiki.t2linux.org/#guides-and-similar) could make it feel more like macOS, but comes at the cost of using a legacy display server (X11) instead of Wayland, potentially exposing other issues, like blurry display scaling.

Let me know what you think.

2023-12-20 06:57 UTC, AdityaGarg8 commented
I leave this to other ma

> The reason I think we should reference it here is because of the note we have added to it:
> 
> > Works, but isn't as great as on macOS
> 
> On the other wiki page you linked, it says that you can obtain this:
> 
> > Implement macOS-like Keyboard and trackpad experience
> 
> I don't think adding a casual mention to it would hurt. Something like this:
> 
> > Works, but isn't as great as on macOS (no force touch or palm rejection). Some models have deadzones on the edges of their trackpads where swipes along the trackpad that start in these deadzones will not be registered. Using Synaptics + X11 as per [this guide](https://wiki.t2linux.org/#guides-and-similar) could make it feel more like macOS, but comes at the cost of using a legacy display server (X11) instead of Wayland, potentially exposing other issues, like blurry display scaling.
> 
> Let me know what you think.

I leave this to other maintainers @Redecorating @sharpenedblade

2023-12-20 07:14 UTC, sharpenedblade commented
> https://gist.github.com/smileBeda/f0452f0d7f1f6d8aa772603411f7876f

This config doesnt seem to be doing anything that cant be done with libinput, we should try to get it working on wayland before puting this on the wiki (once its on the wiki people are going to use it and we "have" to support them). [touchpad preasure](https://wayland.freedesktop.org/libinput/doc/latest/touchpad-pressure-debugging.html) and [palm rejection](https://wayland.freedesktop.org/libinput/doc/latest/palm-detection.html) is supported, we just need to set the quirks, the touchpad edge bug is fixed with [this](https://github.com/t2linux/linux-t2-patches/commit/af351299c1bea3212fa934bb3eecef0c9a9e52a0) commit.

We can merge this now and change it later, or wait for proper libinput support. @Redecorating

2023-12-22 07:21 UTC, AdityaGarg8 reviewed
Let's merge this after addressing all this?

2023-12-22 07:21 UTC, AdityaGarg8 commented on docs/state.md
> +|AMD GPUs|🟡 Partially working||Changing resolution, using DRI_PRIME and doing various other things can cause crashes, but `echo high \| sudo tee /sys/bus/pci/drivers/amdgpu/0000:??:??.?/power_dpm_for
Is this still an issue?

2023-12-22 07:21 UTC, AdityaGarg8 commented on docs/contribute.md
> +- [AdityaGarg8](https://github.com/AdityaGarg8) - Current maintainer of Ubuntu. Has also Current maintainer of Ubuntu. Has also helped in writing T2 kernel patches and upstreaming various patches. Do
I messed up a line here, could you please correct it

2023-12-22 20:06 UTC, sharpenedblade commented on docs/state.md
> +|AMD GPUs|🟡 Partially working||Changing resolution, using DRI_PRIME and doing various other things can cause crashes, but `echo high \| sudo tee /sys/bus/pci/drivers/amdgpu/0000:??:??.?/power_dpm_for
yes

2023-12-22 23:53 UTC, netnef commented
> > https://gist.github.com/smileBeda/f0452f0d7f1f6d8aa772603411f7876f
> 
> This config doesnt seem to be doing anything that cant be done with libinput, we should try to get it working on wayland before puting this on the wiki (once its on the wiki people are going to use it and we "have" to support them). [touchpad preasure](https://wayland.freedesktop.org/libinput/doc/latest/touchpad-pressure-debugging.html) and [palm rejection](https://wayland.freedesktop.org/libinput/doc/latest/palm-detection.html) is supported, we just need to set the quirks, the touchpad edge bug is fixed with [this](https://github.com/t2linux/linux-t2-patches/commit/af351299c1bea3212fa934bb3eecef0c9a9e52a0) commit.
> 
> We can merge this now and change it later, or wait for proper libinput support. @Redecorating

The config is already on the wiki: https://wiki.t2linux.org/#guides-and-similar

Perhaps we should clarify that it's unsupported by the t2linux maintainers there.

2023-12-23 00:24 UTC, netnef commented
I updated two pages to address concerns from @sharpenedblade. Let me know what you think.

* https://netnef.github.io/wiki/#guides-and-similar
* https://netnef.github.io/wiki/state/

2023-12-23 02:19 UTC, sharpenedblade commented
The deadzone problem is fixed a few days ago, we can merge once thats removed

2023-12-23 03:24 UTC, netnef commented
I removed the deadzones remark. @AdityaGarg8 are we good to merge?

2023-12-23 03:34 UTC, AdityaGarg8 commented
Looks like we are

2023-12-23 03:36 UTC, merged

2023-12-23 06:06 UTC, netnef commented
👍 Thank you all for the help. Glad we got these pages updated. Long overdue.