wifi: model, chip, fw table
t2linux/wiki pull request #56
Opened 2021-07-13 01:51 UTC by Redecorating

this is a draft, if ppl have missing bits, tell me or add them

2021-07-22 08:59 UTC, networkException requested changes
Awesome work! I added a few comments all on the same topic basically, otherwise everything looks great

2021-07-22 08:59 UTC, networkException commented on docs/guides/wifi.md
> +> Note: If you are unable to get the firmware even after following guide for other models, you might need to extract firmware from macOS at this point. See the instructions in [On any OS](https://wik
Maybe this could actually be merged with the table. In that case "Is my model supported" might better be "Getting the right firmware" or something

2021-07-22 08:59 UTC, networkException commented on docs/guides/wifi.md
> +    - If you need Big Sur firmware, then it is avaliable in `/usr/share/firmware/wifi` in macOS Big Sur installations, or online at [https://github.com/Redecorating/archinstall-mbp/tree/packages/appl
Same here basically, there's duplication with the On macOS section and it is probably way easier to just have download options in the table (or at least below it somewhere)

2021-07-25 11:53 UTC, Redecorating commented
I've reorganised the order of instructions for getting wifi firmware.

2021-07-25 12:12 UTC, networkException approved these changes
LGTM :tada:

2021-07-25 12:12 UTC, AdityaGarg8 reviewed
You could bold the names like mbp-fedora etc. The Ubuntu kernels with wifi patch link should be added ad iso with the patches is not available I guess. For the 16.1 firmware link, it can be clarified that it is a quicker way to get this thing done.

2021-07-25 12:18 UTC, networkException commented
The changes requsted by AdityaGarg8 seem fair

2021-07-26 06:55 UTC, Redecorating commented
I think that should be better, I don't know when there'll be an ubuntu iso with the 16x-wifi kernel, but I've added instructions to install it with `apt`

2021-07-26 07:04 UTC, AdityaGarg8 commented
Are the ubuntu kernels being installed using apt?

2021-07-26 07:05 UTC, AdityaGarg8 commented
I mean are they going to the marcosfad's server from where apt gets them

2021-07-26 07:06 UTC, AdityaGarg8 commented
Downloading from the repo on github is much better (atleast for me, don't know about the rest).

2021-07-26 07:08 UTC, Redecorating commented
The kernel is now here https://mbp-ubuntu-kernel.herokuapp.com so it is on the repo

2021-07-26 07:10 UTC, AdityaGarg8 commented
Great. But I am not sure whether it will be updated that regularly as your and mine repo are

2021-07-26 07:16 UTC, AdityaGarg8 commented
You may give alternative links for Ubuntu kernels for those who like to be up to date with latest kernel

2021-07-26 08:51 UTC, AdityaGarg8 commented
In the **Big sir firmware** section, you may split the paragraph in such a way that each district has a separate one. It makes it look better and easier to understand.

2021-07-26 12:31 UTC, merged

2021-07-26 12:31 UTC, networkException commented
:tada: